### PR TITLE
simplify systemd unit file

### PR DESCRIPTION
**Pull request by fkooman**
PR for issue #133.

### CODE REVIEW

**Comment by aflyhorse** [comment]
IMHO, the original "tinc.service" seems to act as a general all-in-one switch for all other tinc services.
I'm not sure if removing is proper.

**Comment by fkooman** [comment]
Ah, if that is a feature that is being used then that makes sense... It seems it is based on the Debian OpenVPN systemd unit. 

Do you have any idea how to fix the issue on CentOS where the current service file does not wait for the network to be up to start? https://bugzilla.redhat.com/show_bug.cgi?id=1394512.

**Comment by aflyhorse** [comment]
I thought "After=network.target" should work. On the other side, tweaks must be made in actual C/C++ code, to make it more friendly to network freak.
```
If you are a developer, instead of wondering what to do about network.target, please just fix your program to be friendly to dynamically changing network configuration. That way you will make your users happy because things just start to work, and you will get fewer bug reports as your stuff is just rock solid.
```
source: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

**Comment by heroxbd** [comment]
Shall close this PR?

BTW, greetings @aflyhorse !

**Comment by aflyhorse** [comment]
I'm suffering from that tinc@xxx.service doesn't start automatically in CentOS 7.x. It's working nice in Fedora 25+ however, so it might be another problem. Seems the distro files have be rewritten, @fkooman are you still interested in the PR?

BTW, Greetings @heroxbd , thank you for introducing tinc to me. I've been using it to bypass numerous firewalls and routers.

**Comment by tomberek** [comment]
Close?

**Comment by fkooman** [comment]
I'm currentl not using tinc, so maybe it is better if someone else took over, or indeed close the PR.

**Comment by aflyhorse** [comment]
The problem in CentOS 7.x has already fixed. I suggest keep the current status and close this PR.

**Comment by fangfufu** [comment]
Closing the PR, as per suggestion by @tomberek and @aflyhorse , and also @fkooman no longer uses tinc.

**Pull request closed without merging**
