### PR TITLE
initial epoll & initial tx buffering support

### PR DESCRIPTION
**Pull request by splitice**
adds epoll and basic tx buffers as per research paper https://www.cs.cornell.edu/courses/cs5413/2014fa/projects/group_of_ej222_jj329_jsh263/ as developed in #266

### CODE REVIEW

**Comment by splitice** [comment]
Packet buffers are as defined in the paper. They arent particularly useful yet outside of broacasted packets.

Tun ARP messages would probably be the main user of the buffering capability?

**Comment by gsliepen** [comment]
> adds epoll and basic tx buffers

It would be nice to split this into two pull requests, one for `epoll` support and one for `sendmmsg()`, as I think they are orthogonal.

> Packet buffers are as defined in the paper. They arent particularly useful yet outside of broadcasted packets.
> 
> Tun ARP messages would probably be the main user of the buffering capability?

Why not use it for all UDP packets? Just always add packets to the socket's `packet_buffer`, and then call `send_buffered_packets()` if either the packet buffer is full, or right before calling `select()` or `epoll_wait()`.

**Comment by splitice** [comment]
As per the issue larger architectual issues prevent that currently. All fds would need to be non-blocking.

I'm not super against splitting this however I feel they both support each other and would likely conflict if your suggestion was implemented.

**Comment by gsliepen** [comment]
All fds are non-blocking. Also, I still don't see how the sendmmsg and epoll parts depend on each other. There is nothing in your code that suggests so.

**Comment by splitice** [comment]
> and then call send_buffered_packets() if either the packet buffer is full, or right before calling select() or epoll_wait().

Introduces the expected cross dependency mentioned. I'd consider this packet buffering functional but basic currently. It's greatly extended in the vhost net work (which also depends on epoll_wait).

Unfortunately I have limited time available so want to merge as much as possible where possible to keep conflicts to a bare minimum.

---

We discussed making the loop safe to handle multiple io operations per loop, I'd prefer if you were to make that commit. At this stage I don't feel confident enough in my undestanding of that area.

**Comment by splitice** [comment]
Since hashtable has merged I'll start work on getting this up to merge.

Removed the splay each iteration of the io tree, this should boost performance on the epoll path. Needs further testing though.

I'm looking into the multiple IO ops through the event paths.

**Comment by splitice** [comment]
It would appear that epoll_wait is more efficient than doing multiple read/writes per cycle even at moderate rates of transfer (and significantly better at low rates). The 2x syscall for every socket quickly dwarfs gains from reduction in epoll_waits.

**Comment by splitice** [comment]
I'm thinking I'll submit a seperate PR at around a0ff2d874b39959066994b5486807fdd7a638e40 with just the epoll parts.

I think a more general cleanup and refactor of net_packet as discussed in #319 would be better done before packet buffers are added (as nice as they are).

**Comment by splitice** [comment]
Closing PR. Will resubmit packet buffers at a later date. Epoll V2 pr already sent.

**Pull request closed without merging**
