### PR TITLE
Add localization support using gettext

### PR DESCRIPTION
**Pull request by hg**
Is there any interest in having tinc available in multiple languages, not just English?

This PR adds gettext support and wraps every (I think) user-facing translatable string with the `_()` macro.

Incidentally, it also fixes a couple of logging bugs in Solaris-specific code.

Man pages were not changed. It's a huge job that could be done next.

I know it's a huge diff, but the vast majority of it is the auto-generated `.pot` template which does not require much attention.

Tests:

- https://github.com/hg/tinc/actions/runs/1123359114
- https://github.com/hg/tinc/actions/runs/1123297098
- https://github.com/hg/tinc/actions/runs/1123134191
- https://builds.sr.ht/~reducer/job/565004
- https://builds.sr.ht/~reducer/job/565005
- https://builds.sr.ht/~reducer/job/565006

---

If you do merge this, I'll start translating tinc into Russian. For other languages we can use one of these services:

- https://weblate.org/
- https://translationproject.org/

and rely on the community for help.

For example:

- https://hosted.weblate.org/projects/tinc/

(I'll remove this project after this PR is merged to let you register the name.)

Another example from the sssd project:

- https://github.com/SSSD/sssd
- https://translate.fedoraproject.org/projects/sssd/

---

I translated a few strings just to show that it works:

https://github.com/hg/tinc/tree/l10n

```
Usage: tincd [option]...

  -c, --config=DIR              Читать настройки из директории DIR.
  -D, --no-detach               Не отключаться от терминала и не переходить в фон.
  -d, --debug[=LEVEL]           Увеличить подробность журналирования или установить уровень на LEVEL.
  -n, --net=NETNAME             Подключиться к сети NETNAME.
  -L, --mlock                   Запретить сброс tinc в файл подкачки.
      --logfile[=FILENAME]      Включить журналирование в файл.
  -s  --syslog                  Use syslog instead of stderr with --no-detach.
      --pidfile=FILENAME        Write PID and control socket cookie to FILENAME.
      --bypass-security         Отключает проверки безопасности в протоколе (для отладки).
  -o, --option[HOST.]KEY=VALUE  Set global/host configuration value.
  -R, --chroot                  Выполнить chroot в директорию NET при запуске.
  -U, --user=USER               Запускать под пользователем USER.
      --help                    Показать справку и выйти.
      --version                 Показать информацию о версии и выйти.

Сообщайте о проблемах на tinc@tinc-vpn.org.
```

### CODE REVIEW

**Comment by gsliepen** [comment]
> Is there any interest in having tinc available in multiple languages, not just English?

Well, tinc used to support gettext, but this was dropped in commit 4c85542894f7fca823b119b05e07179deb24229a because there was not much effort in actually maintaining translations. So giving this past experience, I think it doesn't make sense unless we have some way to incentivize translations being made and maintained.

**Comment by hg** [comment]
Ah, sorry, I didn't know about that. I can maintain one translation, and from looking at other projects, even pretty low-level components like sssd, I've been thinking along "build and they will come" lines, but with this history in mind it's probably not worth it.

**Comment by fangfufu** [comment]
Well, if we ever want to work on issue https://github.com/gsliepen/tinc/issues/118, then we have to revisit this pull request.

**Comment by hg** [comment]
I forgot to delete the project and somebody has started translating it into Norwegian.

https://hosted.weblate.org/projects/tinc/tinc/nb_NO/

I'll see how it goes and will keep working on the Russian translation for the time being.

**Pull request closed without merging**
