### PR TITLE
Test pull request to see if windows CI works (do not merge) 

### PR DESCRIPTION
**Pull request by fangfufu**
**Do not merge**

I can't seem to trigger CI runs on my own forks, without creating a pull request.

### CODE REVIEW

**Comment by fangfufu** [comment]
It appears that CI is broken right now... The Github workflow isn't running at all.

**Comment by gsliepen** [comment]
It's because you pushed exactly the same commit as in #308. I think GitHub notices it's not a new commit hash and thus skips checks.

**Comment by fangfufu** [comment]
@gsliepen , I created this new pull request because the old one was only running the workflows outside of Github. I have just created a new commit with a dummy file, and it is still not running the workflows from Github itself.

**Comment by fangfufu** [comment]
I recommend continuing the discussion of Github workflows not running at https://github.com/gsliepen/tinc/issues/310

**Comment by fangfufu** [comment]
Okay, Github workflow issue was due to Github infrastructure. I am still investigating the problem with Windows CI workflow.

**Pull request closed without merging**
