### PR TITLE
OpenSSL: Fix compilation without deprecated APIs or ENGINE support

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by mark-stopka** [comment]
Is there some problem with merging this one? It has no conflicts...

**Comment by neheb** [comment]
No interest probably.

**Comment by mark-stopka** [comment]
@neheb, it seems the upstream of this project is pretty dead, maybe worth forking it... I really like the plans for Tinc 2.0., but with this speed it's never going to get there.

**Comment by neheb** [comment]
Oh. This seems to have gotten merged back in December.

**Comment by neheb** [comment]
This was merged it seems...

**Pull request closed without merging**
